version: '3'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=Etc/UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    networks:
      - mompi

  server:
    image: mompi_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CLIENT_URL=redis://redis:6379/0
      - PRONTO_GITHUB_ACCESS_TOKEN
    command: rackup
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mompi

volumes:
  postgres-data:
    driver: local

networks:
  mompi:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
